# Generated by Django 3.0.5 on 2020-05-30 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 사용자')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='이메일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='게시판 이름')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('content', models.TextField(verbose_name='내용')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Board', verbose_name='게시판')),
            ],
            options={
                'ordering': ['-is_notice', '-date_created'],
            },
        ),
    ]
